name = "Sparrow"
uuid = "e85e9086-995e-43cb-b1fa-761c47980264"
authors = ["Michael Bell <mmbell@colostate.edu> and contributors"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ClusterManagers = "34f1f09b-3a8b-5176-ab39-66d58a4d544e"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Daisho = "0095e6a3-0a19-4629-8616-db2ab031b187"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DistributedData = "f6a0035f-c5ac-4ad0-b410-ad102ced35df"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SlurmClusterManager = "c82cd089-7bf7-41d7-976b-6b5d413cbe0a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ArgParse = "1.2.0"
CairoMakie = "0.15.8"
ClusterManagers = "2.0.0"
ColorSchemes = "3.31.0"
Dates = "1.11.0"
Distributed = "1.11.0"
DistributedData = "0.2.0"
FileWatching = "1.11.0"
GeoMakie = "0.7.16"
Images = "0.26.2"
Makie = "0.24.8"
NCDatasets = "0.14.11"
Printf = "1.11.0"
Random = "1.11.0"
SlurmClusterManager = "1.1.0"
Statistics = "1.11.1"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
